import type { Metadata } from "next";
import localFont from 'next/font/local'
import { Urbanist } from "next/font/google";
import "./globals.css";
import Header from "./header";
import Head from "next/head";

 
// Font files can be colocated inside of `pages`
const seasons = localFont({ 
  src: './fonts/theseasons-reg-webfont.woff2',
  variable: '--font-the-seasons'
})

const urbanist = Urbanist({
  subsets: ["latin"],
  variable: "--font-urbanist"
})

const beth_ellen = localFont({
  src: "./fonts/BethEllen.otf",
  variable: "--font-beth-ellen"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${seasons.variable} font-serif, ${beth_ellen.variable} font-sans, ${urbanist.variable}, font-mono`}>
        <Header />
        <main>
          {children}
        </main>
        </body>
    </html>
  );
}
